services:

  app:
    build:
      context: . # путь к Dockerfile
      dockerfile: Dockerfile # имя Dockerfile
    container_name: 06-05-bot # имя контейнера
    env_file:
       - .env # путь к файлу с переменными окружения

    command: sh -c "python main.py"

    logging: # настройка логов
      options:
        max-size: '500M' # максимальный размер логов
        max-file: '5' # максимальное количество файлов логов
    restart: always # перезапуск контейнера
    volumes:
      - .:/app # маппинг файлов
    depends_on: # список зависимостей
      - db

  db:
    image: postgres:15.4-alpine3.18 # образ на основании которого будет создан контейнер
    container_name: 06-05-db
    hostname: bot-db # имя хоста для подключения из другого контейнера
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
